services:
  forgejo_event_listener:
    image: re2bit/forgejo_event_listener:${TAG:-latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ../.env
